url: "http://hi-rustin.rs"

highlighter: rouge
permalink: /:title/
markdown: kramdown

future: true

plugins:
  - jekyll-feed
  - jekyll-redirect-from

collections:
  presentations:
    output: true
    permalink: /:title/

  podcasts:

exclude: ['node_modules', 'scripts', 'vendor']
